name: Kommons-Gated-PR-Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
    - uses: actions/checkout@v2
      with:
      #Using Main branch of Karina Repository
       repository: flanksource/karina
    - run: |
        module=$(cat go.mod | grep github.com/flanksource/kommons | awk '{print $2}')
        go mod edit -replace github.com/flanksource/kommons@$module=github.com/${{ github.repository }}@${{ github.head_ref }}  
        cat go.mod
        go mod tidy
      name: replace Module
    - name: Test Make Linux
      run: make linux
    - uses: actions/upload-artifact@v2
      with:
        name: karina
        path: ./.bin/karina
  e2e:
    runs-on: ubuntu-20.04
    needs:
      - build
    env:
      FILE_CHANGES_TO_CORE_ARTIFACTS: ${{ needs.gates.outputs.fileChangesToCoreArtifacts == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.18.6
        suite:
          - minimal
    steps:
      - uses: actions/checkout@v2
        with:
      #Using Main branch of Karina Repository
          repository: flanksource/karina
      - uses: actions/download-artifact@v2
        with:
          name: karina
          path: ./.bin
      - name: Run e2e testing script
        id: e2e
        env:
          GIT_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          SUITE: ${{ matrix.suite }}
          KUBERNETES_VERSION: ${{matrix.k8s}}
          BUILD: test (${{matrix.k8s}}, ${{ matrix.suite }})
          ADDITIONAL_CONFIG: -c test/hosted-tests.yaml
        run: ./test/test.sh
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: ignore
          name: test-results-${{matrix.k8s}}-${{matrix.suite}}
          path: test-results/
      - name: Upload snapshots
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: ignore
          name: snapshot-${{matrix.k8s}}-${{matrix.suite}}
          path: artifacts/snapshot.zip
      - name: Generate Kind logs
        run: .bin/kind export logs --name=kind-${{matrix.suite}}-${{matrix.k8s}} artifacts/kind-logs
      - name: Upload Kind logs
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: ignore
          name: kind-logs-${{matrix.k8s}}-${{matrix.suite}}
          path: artifacts/kind-logs
